### ISSUE TITLE
能多加一些接口吗？只有一个百度的不太够用

### ISSUE THREAD

**Issue by fs920105** [chflame163/ComfyUI_BaiduTranslate#1]
建议能加上阿里，腾讯，火山引擎的接口，这些都有免费额度，只有一个百度的不太够用

**Comment by chflame163** [comment]
谢谢反馈，我在认真考虑这个建议。据我了解，阿里、腾讯、火山的翻译接口都需要引用他们的依赖库，但是我不希望把python环境弄得更混乱。我发现小牛的API比较干净并且有足够的免费额度（每天20万字符），所以正在进行准备。相信很快会有新的版本更新。

**Comment by fs920105** [comment]
> 谢谢反馈，我在认真考虑这个建议。据我了解，阿里、腾讯、火山的翻译接口都需要引用他们的依赖库，但是我不希望把python环境弄得更混乱。我发现小牛的API比较干净并且有足够的免费额度（每天20万字符），所以正在进行准备。相信很快会有新的版本更新。

如果是每天20万那可太棒了，谢谢你设计的插件，给你点赞。

**Comment by chflame163** [comment]
已提交更新。
